# UTS-2 My Songs for You

## Lacrimosa - Wolfgang Amadeus Mozart

{{< video https://youtu.be/MafAZeag1_0?si=FawnE8ZtdpoKFmuD>}}

> **[Chorus]**  
> Lacrimosa dies illa  
> Qua resurget ex favilla  
> Judicandus homo reus  
> Lacrimosa dies illa  
> Qua resurget ex favilla  
> Judicandus homo reus  
>
> **[Bridge]**  
> Huic ergo parce Deus  
> Pie Jesu, Jesu Domine  
>
> **[Outro]**  
> Dona eis requiem  
> Dona eis requiem  
> Amen  

---

## Hymne HMIF ITB - HMIF ITB

{{< video https://youtu.be/k2txZWSVV5s?si=Evy8HxhIVuScTeBn>}}

> **[Verse 1]**  
> untaian benang takdir  
> mempersatukan kita  
> teknik informatika  
> berjiwa kesatria  
>
> **[Verse 2]**  
> adalah mimpi kita  
> gapai sejuta cita  
> dengan satu semangat  
> dalam kebersamaan  
>  
> **[Reff]**  
> persaudaraan diantara kita  
> tak terlepaskan tak tergantikan  
> kami disini berdiri dengan tegar  
> mengobarkan semangat demi nusa bangsa  
> kami bertekad untuk berbakti  
> pada Tuhan, bangsa, dan almamater  
> pada Tuhan, bangsa, dan almamater  

---

## Kipas Angin Kesedot Sampah - Orkes Pensil Alis 

{{< video https://www.youtube.com/watch?v=l21omEixE1c>}}

> Kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
>  
> Kipas angin kesedot sampah   
> Oh kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
>
> Buat sayangku Orocimaru di Kualanamu  
> Aku dan kamu ini ibaratnya seperti indomales dan alfamales  
> Kita sering berdekat-dekatan  
> Tetapi tidak mungkin untuk bersatu  
>
> Ho-oh-oh  
>
> Kipas angin kesedot sampah  
> Oh kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
>
> Buat sayangku Eto'o PNS di Kamerun  
> Aku ini di hadapanmu  
> Ibaratnya seperti krupuk di warung mie ayam  
> Aku selalu ada tetapi bukan menjadi pilihan yang utama  
>
> Ho-oh-oh ho-oh-oh-oh
>
> Kipas angin kesedot sampah  
> Oh kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
>
> Ya salam-salam dari bapak Parjo  
> Salam buat bapak Cici  
> Salamnya salam kompak selalu  
> Dari Binasrul salam buat pokemon  
> Salamnya salam sayang selalu  
> Buat bapak, pak mulih pak waduh  
>
> Ho-oh-oh oh-oh-oh oh-oh-oh
>
> Kipas angin kesedot sampah  
> Oh kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
> Kipas angin kesedot sampah  
>
> Orkes pensil alis  
> Orkes pensil alis  
> Orkes pensil alis  
> Orkes pensil alis  